const KEY='hjortemosen_data_v1';
const DRAFT_KEY='hjortemosen_booking_draft_v1';
const defaults={bookings:[],renters:[],blacklist:[],settings:{memberPrice:1000,otherPrice:1500,deposit:500}};
let data=load();let monthCursor=new Date();let deferredPrompt=null;let draftTimer=null;let formHydrating=false;
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function isoLocal(d){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function fmtDate(s){return new Intl.DateTimeFormat('da-DK',{dateStyle:'long'}).format(new Date(s+'T12:00:00'))}
function money(n){return new Intl.NumberFormat('da-DK').format(Number(n||0))+' kr.'}
function timeNow(){return new Intl.DateTimeFormat('da-DK',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='calendar')renderCalendar();window.scrollTo({top:0,behavior:'smooth'})}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function typeLabel(t){return t==='member'?'Haveforening':t==='friend'?'Ven':'Andre'}
function isBlacklisted(name,gardenNo=''){return data.blacklist.some(x=>x.name.trim().toLowerCase()===name.trim().toLowerCase() || (gardenNo&&x.house&&x.house.trim().toLowerCase()===gardenNo.trim().toLowerCase()))}
function renderStats(){const today=isoLocal(new Date());const future=data.bookings.filter(b=>b.date>=today);const unpaid=future.filter(b=>!b.paid);$('#stats').innerHTML=`<div class="stat"><strong>${future.length}</strong><span>Kommende bookinger</span></div><div class="stat"><strong>${unpaid.length}</strong><span>Mangler betaling</span></div><div class="stat"><strong>${money(unpaid.reduce((s,b)=>s+(+b.price||0),0))}</strong><span>Udestående leje</span></div>`}
function renderUpcoming(){const today=isoLocal(new Date());const arr=[...data.bookings].filter(b=>b.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,12);$('#upcomingList').innerHTML=arr.length?arr.map(b=>`<div class="list-item" data-edit="${b.id}"><div><strong>${fmtDate(b.date)}</strong><small>${esc(b.name)}${b.houseNo?' · Have '+esc(b.houseNo):''} · ${typeLabel(b.type)}</small></div><div><span class="badge ${b.paid?'paid':'unpaid'}">${b.paid?'Betalt':'Ikke betalt'}</span><small>${money(b.price)}</small></div></div>`).join(''):'<p class="muted">Ingen kommende bookinger.</p>';$$('[data-edit]').forEach(x=>x.onclick=()=>editBooking(x.dataset.edit))}
function renderCalendar(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthLabel').textContent=new Intl.DateTimeFormat('da-DK',{month:'long',year:'numeric'}).format(monthCursor);const first=(new Date(y,m,1).getDay()+6)%7;const days=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const date=isoLocal(new Date(y,m,d));const b=data.bookings.find(x=>x.date===date);const today=date===isoLocal(new Date());html+=`<button class="day ${b?(b.paid?'booked':'unpaid'):''} ${today?'today':''}" data-date="${date}"><span class="date">${d}</span>${b?`<div class="who">${esc(b.name)}</div>`:''}</button>`}$('#calendarGrid').innerHTML=html;$$('.day[data-date]').forEach(el=>el.onclick=()=>{const b=data.bookings.find(x=>x.date===el.dataset.date);b?editBooking(b.id):(resetForm(true),$('#bookingDate').value=el.dataset.date,scheduleDraftSave(),go('booking'))})}
$('#prevMonth').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderCalendar()};
function renderRenters(){const q=$('#renterSearch').value.trim().toLowerCase();const arr=[...data.renters].filter(r=>!q||`${r.name} ${r.houseNo||''}`.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'da'));$('#renterList').innerHTML=arr.length?arr.map(r=>`<div class="list-item"><div><strong>${esc(r.name)}</strong><small>${r.houseNo?'Have '+esc(r.houseNo):'Intet have nummer'}${r.phone?' · '+esc(r.phone):''}</small></div><div><button class="secondary" data-use-renter="${r.id}">Book</button> <button class="danger" data-del-renter="${r.id}">Slet</button></div></div>`).join(''):'<p class="muted">Ingen gemte lejere.</p>';$$('[data-use-renter]').forEach(b=>b.onclick=()=>{resetForm(true);fillRenter(data.renters.find(r=>r.id===b.dataset.useRenter));go('booking')});$$('[data-del-renter]').forEach(b=>b.onclick=()=>{if(confirm('Slet lejeren fra listen?')){data.renters=data.renters.filter(r=>r.id!==b.dataset.delRenter);save()}})}
$('#renterSearch').oninput=renderRenters;
function renderSavedRenter(){const sel=$('#savedRenter');sel.innerHTML='<option value="">— Ny eller ikke gemt —</option>'+[...data.renters].sort((a,b)=>a.name.localeCompare(b.name,'da')).map(r=>`<option value="${r.id}">${esc(r.name)}${r.houseNo?' · Have '+esc(r.houseNo):''}</option>`).join('')}
$('#savedRenter').onchange=e=>{const r=data.renters.find(x=>x.id===e.target.value);if(r)fillRenter(r)};
function fillRenter(r){formHydrating=true;$('#name').value=r.name||'';$('#houseNo').value=r.houseNo||'';$('#phone').value=r.phone||'';$('#email').value=r.email||'';const radio=document.querySelector(`[name=renterType][value="${r.type||'member'}"]`);if(radio)radio.checked=true;applyPrice();checkWarning();formHydrating=false;scheduleDraftSave()}
function applyPrice(){const type=$('[name=renterType]:checked').value;$('#price').value=type==='member'?data.settings.memberPrice:data.settings.otherPrice;if(!formHydrating)scheduleDraftSave()}
$$('[name=renterType]').forEach(r=>r.onchange=applyPrice);
function checkWarning(){const name=$('#name').value,gardenNo=$('#houseNo').value,date=$('#bookingDate').value,id=$('#bookingId').value;const msgs=[];if(name&&isBlacklisted(name,gardenNo))msgs.push('Denne person eller dette have nummer er på blacklist og kan ikke bookes.');if(date&&data.bookings.some(b=>b.date===date&&b.id!==id))msgs.push('Datoen er allerede booket.');const w=$('#bookingWarning');w.textContent=msgs.join(' ');w.classList.toggle('hidden',!msgs.length);return msgs.length===0}
['#name','#houseNo','#bookingDate'].forEach(s=>$(s).addEventListener('input',checkWarning));
function collectDraft(){return {id:$('#bookingId').value,date:$('#bookingDate').value,name:$('#name').value,houseNo:$('#houseNo').value,phone:$('#phone').value,email:$('#email').value,type:$('[name=renterType]:checked')?.value||'member',price:$('#price').value,deposit:$('#deposit').value,paid:$('#paid').checked,depositPaid:$('#depositPaid').checked,saveRenter:$('#saveRenter').checked,notes:$('#notes').value,savedAt:new Date().toISOString()}}
function hasDraftContent(d){return Boolean(d.id||d.date||d.name.trim()||d.houseNo.trim()||d.phone.trim()||d.email.trim()||d.notes.trim())}
function setAutoSaveStatus(text,isSaved=true){const el=$('#autoSaveStatus');if(!el)return;el.textContent=text;el.classList.toggle('pending',!isSaved)}
function saveDraft(manual=false){if(formHydrating)return;const draft=collectDraft();if(hasDraftContent(draft)){localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));setAutoSaveStatus(`${manual?'Kladde gemt manuelt':'Automatisk gemt'} kl. ${timeNow()}`);if(manual)toast('Kladde gemt manuelt')}else{localStorage.removeItem(DRAFT_KEY);setAutoSaveStatus('Kladde gemmes automatisk på denne enhed')}}
function scheduleDraftSave(){if(formHydrating)return;setAutoSaveStatus('Gemmer kladde…',false);clearTimeout(draftTimer);draftTimer=setTimeout(()=>saveDraft(false),450)}
function restoreDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(!d||!hasDraftContent(d))return;formHydrating=true;$('#bookingId').value=d.id||'';$('#bookingFormTitle').textContent=d.id?'Rediger booking':'Ny booking';$('#bookingDate').value=d.date||'';$('#name').value=d.name||'';$('#houseNo').value=d.houseNo||'';$('#phone').value=d.phone||'';$('#email').value=d.email||'';const radio=document.querySelector(`[name=renterType][value="${d.type||'member'}"]`);if(radio)radio.checked=true;$('#price').value=d.price||'';$('#deposit').value=d.deposit||data.settings.deposit;$('#paid').checked=!!d.paid;$('#depositPaid').checked=!!d.depositPaid;$('#saveRenter').checked=d.saveRenter!==false;$('#notes').value=d.notes||'';$('#deleteBooking').classList.toggle('hidden',!d.id);formHydrating=false;checkWarning();setAutoSaveStatus(`Kladde gendannet fra kl. ${new Intl.DateTimeFormat('da-DK',{hour:'2-digit',minute:'2-digit'}).format(new Date(d.savedAt||Date.now()))}`)}catch{localStorage.removeItem(DRAFT_KEY)}}
function clearDraft(){clearTimeout(draftTimer);localStorage.removeItem(DRAFT_KEY);setAutoSaveStatus('Kladde gemmes automatisk på denne enhed')}
function resetForm(removeDraft=true){formHydrating=true;const f=$('#bookingForm');f.reset();$('#bookingId').value='';$('#bookingFormTitle').textContent='Ny booking';$('#deleteBooking').classList.add('hidden');$('#deposit').value=data.settings.deposit;$('#saveRenter').checked=true;applyPrice();formHydrating=false;checkWarning();if(removeDraft)clearDraft()}
$('#resetBooking').onclick=()=>resetForm(true);
$('#saveDraft').onclick=()=>saveDraft(true);
$('#bookingForm').addEventListener('input',scheduleDraftSave);
$('#bookingForm').addEventListener('change',scheduleDraftSave);
$('#bookingForm').onsubmit=e=>{e.preventDefault();if(!checkWarning())return;const b={id:$('#bookingId').value||uid(),date:$('#bookingDate').value,name:$('#name').value.trim(),houseNo:$('#houseNo').value.trim(),phone:$('#phone').value.trim(),email:$('#email').value.trim(),type:$('[name=renterType]:checked').value,price:+$('#price').value||0,deposit:+$('#deposit').value||0,paid:$('#paid').checked,depositPaid:$('#depositPaid').checked,notes:$('#notes').value.trim(),updatedAt:new Date().toISOString()};const i=data.bookings.findIndex(x=>x.id===b.id);i>=0?data.bookings[i]=b:data.bookings.push(b);if($('#saveRenter').checked){const key=b.name.toLowerCase()+'|'+b.houseNo.toLowerCase();const existing=data.renters.find(r=>(r.name.toLowerCase()+'|'+(r.houseNo||'').toLowerCase())===key);const r={id:existing?.id||uid(),name:b.name,houseNo:b.houseNo,phone:b.phone,email:b.email,type:b.type};existing?Object.assign(existing,r):data.renters.push(r)}save();clearDraft();toast('Booking gemt');resetForm(false);go('dashboard')}
function editBooking(id){const b=data.bookings.find(x=>x.id===id);if(!b)return;go('booking');formHydrating=true;$('#bookingId').value=b.id;$('#bookingFormTitle').textContent='Rediger booking';$('#bookingDate').value=b.date;$('#name').value=b.name;$('#houseNo').value=b.houseNo||'';$('#phone').value=b.phone||'';$('#email').value=b.email||'';document.querySelector(`[name=renterType][value="${b.type}"]`).checked=true;$('#price').value=b.price;$('#deposit').value=b.deposit||0;$('#paid').checked=!!b.paid;$('#depositPaid').checked=!!b.depositPaid;$('#notes').value=b.notes||'';$('#deleteBooking').classList.remove('hidden');formHydrating=false;checkWarning();saveDraft(false)}
$('#deleteBooking').onclick=()=>{const id=$('#bookingId').value;if(id&&confirm('Slet bookingen permanent?')){data.bookings=data.bookings.filter(b=>b.id!==id);save();clearDraft();resetForm(false);go('dashboard');toast('Booking slettet')}};
function renderBlacklist(){const el=$('#blacklistList');el.innerHTML=data.blacklist.length?data.blacklist.map(x=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><small>${x.house?'Have '+esc(x.house)+' · ':''}${esc(x.reason)}</small></div><button class="danger" data-del-bl="${x.id}">Fjern</button></div>`).join(''):'<p class="muted">Ingen personer på blacklist.</p>';$$('[data-del-bl]').forEach(b=>b.onclick=()=>{if(confirm('Fjern fra blacklist?')){data.blacklist=data.blacklist.filter(x=>x.id!==b.dataset.delBl);save()}})}
$('#addBlacklist').onclick=()=>$('#blacklistDialog').showModal();$('#saveBlacklist').onclick=e=>{e.preventDefault();if(!$('#blName').value.trim()||!$('#blReason').value.trim())return;data.blacklist.push({id:uid(),name:$('#blName').value.trim(),house:$('#blHouse').value.trim(),reason:$('#blReason').value.trim()});save();$('#blacklistDialog').close();$('#blacklistForm').reset();toast('Tilføjet til blacklist')};
function renderSettings(){$('#memberPrice').value=data.settings.memberPrice;$('#otherPrice').value=data.settings.otherPrice;$('#defaultDeposit').value=data.settings.deposit}
$('#settingsForm').onsubmit=e=>{e.preventDefault();data.settings={memberPrice:+$('#memberPrice').value||0,otherPrice:+$('#otherPrice').value||0,deposit:+$('#defaultDeposit').value||0};save();toast('Indstillinger gemt')};
function backupName(){return `hjortemosen-backup-${isoLocal(new Date())}.json`}
function backupFile(){return new File([JSON.stringify(data,null,2)],backupName(),{type:'application/json'})}
function downloadBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=backupName();document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Sikkerhedskopi gemt')}
$('#exportData').onclick=downloadBackup;
$('#shareData').onclick=async()=>{const file=backupFile();try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'Hjortemosen Booking – sikkerhedskopi',text:'Importér denne fil i Hjortemosen Booking for at overføre bookinger, lejere og blacklist.',files:[file]});toast('Data delt')}else{downloadBackup();alert('Deling af filer understøttes ikke her. Sikkerhedskopien er i stedet gemt, så den kan deles fra appen Arkiver.')}}catch(err){if(err?.name!=='AbortError')alert('Data kunne ikke deles. Prøv at gemme sikkerhedskopien og dele den fra Arkiver.')}};
function bookingOverview(){const arr=[...data.bookings].sort((a,b)=>a.date.localeCompare(b.date));const lines=['HJORTEMOSEN – BOOKINGOVERSIGT',`Oprettet: ${new Intl.DateTimeFormat('da-DK',{dateStyle:'long',timeStyle:'short'}).format(new Date())}`,''];if(!arr.length)lines.push('Ingen bookinger.');for(const b of arr){lines.push(`${fmtDate(b.date)} – ${b.name}${b.houseNo?' – Have '+b.houseNo:''} – ${typeLabel(b.type)} – ${money(b.price)} – ${b.paid?'Betalt':'Ikke betalt'}`);if(b.notes)lines.push(`Bemærkning: ${b.notes}`);lines.push('')}return lines.join('\n')}
$('#shareOverview').onclick=async()=>{const text=bookingOverview();try{if(navigator.share){await navigator.share({title:'Hjortemosen – bookingoversigt',text});toast('Bookingoversigt delt')}else if(navigator.clipboard){await navigator.clipboard.writeText(text);toast('Bookingoversigt kopieret')}else{const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hjortemosen-bookingoversigt-${isoLocal(new Date())}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}}catch(err){if(err?.name!=='AbortError')alert('Bookingoversigten kunne ikke deles.')}};
$('#importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!confirm('Import erstatter de nuværende data. Fortsæt?'))return;data={...defaults,...imported};save();clearDraft();toast('Data importeret')}catch{alert('Filen kunne ikke importeres.')}finally{e.target.value=''}};
$$('[data-print]').forEach(b=>b.onclick=()=>{const w=window.open(b.dataset.print,'_blank');if(!w)return alert('Tillad pop op-vinduer for at printe.');const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);if(!isiOS)setTimeout(()=>{try{w.print()}catch{}},1500)});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderAll(){renderStats();renderUpcoming();renderCalendar();renderRenters();renderSavedRenter();renderBlacklist();renderSettings()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
resetForm(false);restoreDraft();renderAll();
