const KEY='hjortemosen_data_v1';
const defaults={bookings:[],renters:[],blacklist:[],settings:{memberPrice:1000,otherPrice:1500,deposit:500}};
let data=load();let monthCursor=new Date();let deferredPrompt=null;
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function isoLocal(d){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function fmtDate(s){return new Intl.DateTimeFormat('da-DK',{dateStyle:'long'}).format(new Date(s+'T12:00:00'))}
function money(n){return new Intl.NumberFormat('da-DK').format(Number(n||0))+' kr.'}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='calendar')renderCalendar();window.scrollTo({top:0,behavior:'smooth'})}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function typeLabel(t){return t==='member'?'Haveforening':t==='friend'?'Ven':'Andre'}
function isBlacklisted(name,house=''){return data.blacklist.some(x=>x.name.trim().toLowerCase()===name.trim().toLowerCase() || (house&&x.house&&x.house.trim().toLowerCase()===house.trim().toLowerCase()))}
function renderStats(){const today=isoLocal(new Date());const future=data.bookings.filter(b=>b.date>=today);const unpaid=future.filter(b=>!b.paid);$('#stats').innerHTML=`<div class="stat"><strong>${future.length}</strong><span>Kommende bookinger</span></div><div class="stat"><strong>${unpaid.length}</strong><span>Mangler betaling</span></div><div class="stat"><strong>${money(unpaid.reduce((s,b)=>s+(+b.price||0),0))}</strong><span>Udestående leje</span></div>`}
function renderUpcoming(){const today=isoLocal(new Date());const arr=[...data.bookings].filter(b=>b.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,12);$('#upcomingList').innerHTML=arr.length?arr.map(b=>`<div class="list-item" data-edit="${b.id}"><div><strong>${fmtDate(b.date)}</strong><small>${esc(b.name)}${b.houseNo?' · Hus '+esc(b.houseNo):''} · ${typeLabel(b.type)}</small></div><div><span class="badge ${b.paid?'paid':'unpaid'}">${b.paid?'Betalt':'Ikke betalt'}</span><small>${money(b.price)}</small></div></div>`).join(''):'<p class="muted">Ingen kommende bookinger.</p>';$$('[data-edit]').forEach(x=>x.onclick=()=>editBooking(x.dataset.edit))}
function renderCalendar(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthLabel').textContent=new Intl.DateTimeFormat('da-DK',{month:'long',year:'numeric'}).format(monthCursor);const first=(new Date(y,m,1).getDay()+6)%7;const days=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const date=isoLocal(new Date(y,m,d));const b=data.bookings.find(x=>x.date===date);const today=date===isoLocal(new Date());html+=`<button class="day ${b?(b.paid?'booked':'unpaid'):''} ${today?'today':''}" data-date="${date}"><span class="date">${d}</span>${b?`<div class="who">${esc(b.name)}</div>`:''}</button>`}$('#calendarGrid').innerHTML=html;$$('.day[data-date]').forEach(el=>el.onclick=()=>{const b=data.bookings.find(x=>x.date===el.dataset.date);b?editBooking(b.id):(resetForm(),$('#bookingDate').value=el.dataset.date,go('booking'))})}
$('#prevMonth').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderCalendar()};
function renderRenters(){const q=$('#renterSearch').value.trim().toLowerCase();const arr=[...data.renters].filter(r=>!q||`${r.name} ${r.houseNo||''}`.toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'da'));$('#renterList').innerHTML=arr.length?arr.map(r=>`<div class="list-item"><div><strong>${esc(r.name)}</strong><small>${r.houseNo?'Hus '+esc(r.houseNo):'Intet husnummer'}${r.phone?' · '+esc(r.phone):''}</small></div><div><button class="secondary" data-use-renter="${r.id}">Book</button> <button class="danger" data-del-renter="${r.id}">Slet</button></div></div>`).join(''):'<p class="muted">Ingen gemte lejere.</p>';$$('[data-use-renter]').forEach(b=>b.onclick=()=>{resetForm();fillRenter(data.renters.find(r=>r.id===b.dataset.useRenter));go('booking')});$$('[data-del-renter]').forEach(b=>b.onclick=()=>{if(confirm('Slet lejeren fra listen?')){data.renters=data.renters.filter(r=>r.id!==b.dataset.delRenter);save()}})}
$('#renterSearch').oninput=renderRenters;
function renderSavedRenter(){const sel=$('#savedRenter');sel.innerHTML='<option value="">— Ny eller ikke gemt —</option>'+[...data.renters].sort((a,b)=>a.name.localeCompare(b.name,'da')).map(r=>`<option value="${r.id}">${esc(r.name)}${r.houseNo?' · Hus '+esc(r.houseNo):''}</option>`).join('')}
$('#savedRenter').onchange=e=>{const r=data.renters.find(x=>x.id===e.target.value);if(r)fillRenter(r)};
function fillRenter(r){$('#name').value=r.name||'';$('#houseNo').value=r.houseNo||'';$('#phone').value=r.phone||'';$('#email').value=r.email||'';const radio=document.querySelector(`[name=renterType][value="${r.type||'member'}"]`);if(radio)radio.checked=true;applyPrice();checkWarning()}
function applyPrice(){const type=$('[name=renterType]:checked').value;$('#price').value=type==='member'?data.settings.memberPrice:data.settings.otherPrice}
$$('[name=renterType]').forEach(r=>r.onchange=applyPrice);
function checkWarning(){const name=$('#name').value,house=$('#houseNo').value,date=$('#bookingDate').value,id=$('#bookingId').value;const msgs=[];if(name&&isBlacklisted(name,house))msgs.push('Denne person eller dette husnummer er på blacklist og kan ikke bookes.');if(date&&data.bookings.some(b=>b.date===date&&b.id!==id))msgs.push('Datoen er allerede booket.');const w=$('#bookingWarning');w.textContent=msgs.join(' ');w.classList.toggle('hidden',!msgs.length);return msgs.length===0}
['#name','#houseNo','#bookingDate'].forEach(s=>$(s).addEventListener('input',checkWarning));
function resetForm(){const f=$('#bookingForm');f.reset();$('#bookingId').value='';$('#bookingFormTitle').textContent='Ny booking';$('#deleteBooking').classList.add('hidden');$('#deposit').value=data.settings.deposit;$('#saveRenter').checked=true;applyPrice();checkWarning()}
$('#resetBooking').onclick=resetForm;
$('#bookingForm').onsubmit=e=>{e.preventDefault();if(!checkWarning())return;const b={id:$('#bookingId').value||uid(),date:$('#bookingDate').value,name:$('#name').value.trim(),houseNo:$('#houseNo').value.trim(),phone:$('#phone').value.trim(),email:$('#email').value.trim(),type:$('[name=renterType]:checked').value,price:+$('#price').value||0,deposit:+$('#deposit').value||0,paid:$('#paid').checked,depositPaid:$('#depositPaid').checked,notes:$('#notes').value.trim(),updatedAt:new Date().toISOString()};const i=data.bookings.findIndex(x=>x.id===b.id);i>=0?data.bookings[i]=b:data.bookings.push(b);if($('#saveRenter').checked){const key=b.name.toLowerCase()+'|'+b.houseNo.toLowerCase();const existing=data.renters.find(r=>(r.name.toLowerCase()+'|'+(r.houseNo||'').toLowerCase())===key);const r={id:existing?.id||uid(),name:b.name,houseNo:b.houseNo,phone:b.phone,email:b.email,type:b.type};existing?Object.assign(existing,r):data.renters.push(r)}save();toast('Booking gemt');resetForm();go('dashboard')}
function editBooking(id){const b=data.bookings.find(x=>x.id===id);if(!b)return;go('booking');$('#bookingId').value=b.id;$('#bookingFormTitle').textContent='Rediger booking';$('#bookingDate').value=b.date;$('#name').value=b.name;$('#houseNo').value=b.houseNo||'';$('#phone').value=b.phone||'';$('#email').value=b.email||'';document.querySelector(`[name=renterType][value="${b.type}"]`).checked=true;$('#price').value=b.price;$('#deposit').value=b.deposit||0;$('#paid').checked=!!b.paid;$('#depositPaid').checked=!!b.depositPaid;$('#notes').value=b.notes||'';$('#deleteBooking').classList.remove('hidden');checkWarning()}
$('#deleteBooking').onclick=()=>{const id=$('#bookingId').value;if(id&&confirm('Slet bookingen permanent?')){data.bookings=data.bookings.filter(b=>b.id!==id);save();resetForm();go('dashboard');toast('Booking slettet')}};
function renderBlacklist(){const el=$('#blacklistList');el.innerHTML=data.blacklist.length?data.blacklist.map(x=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><small>${x.house?'Hus '+esc(x.house)+' · ':''}${esc(x.reason)}</small></div><button class="danger" data-del-bl="${x.id}">Fjern</button></div>`).join(''):'<p class="muted">Ingen personer på blacklist.</p>';$$('[data-del-bl]').forEach(b=>b.onclick=()=>{if(confirm('Fjern fra blacklist?')){data.blacklist=data.blacklist.filter(x=>x.id!==b.dataset.delBl);save()}})}
$('#addBlacklist').onclick=()=>$('#blacklistDialog').showModal();$('#saveBlacklist').onclick=e=>{e.preventDefault();if(!$('#blName').value.trim()||!$('#blReason').value.trim())return;data.blacklist.push({id:uid(),name:$('#blName').value.trim(),house:$('#blHouse').value.trim(),reason:$('#blReason').value.trim()});save();$('#blacklistDialog').close();$('#blacklistForm').reset();toast('Tilføjet til blacklist')};
function renderSettings(){ $('#memberPrice').value=data.settings.memberPrice;$('#otherPrice').value=data.settings.otherPrice;$('#defaultDeposit').value=data.settings.deposit }
$('#settingsForm').onsubmit=e=>{e.preventDefault();data.settings={memberPrice:+$('#memberPrice').value||0,otherPrice:+$('#otherPrice').value||0,deposit:+$('#defaultDeposit').value||0};save();toast('Indstillinger gemt')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hjortemosen-backup-${isoLocal(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!confirm('Import erstatter de nuværende data. Fortsæt?'))return;data={...defaults,...imported};save();toast('Data importeret')}catch{alert('Filen kunne ikke importeres.')}};
$$('[data-print]').forEach(b=>b.onclick=()=>{const w=window.open(b.dataset.print,'_blank');if(!w)return alert('Tillad pop op-vinduer for at printe.');setTimeout(()=>w.print(),1200)});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderAll(){renderStats();renderUpcoming();renderCalendar();renderRenters();renderSavedRenter();renderBlacklist();renderSettings()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
resetForm();renderAll();
