const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),ctx=vm.createContext({console,Uint8Array,ArrayBuffer,TextEncoder,TextDecoder,setTimeout,clearTimeout,Blob,File});
for(const name of ['contract-libs.js','contracts.js'])vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),ctx);
const ink={png:new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAeAAAAB4CAYAAAAqliEPAAAHt0lEQVR4nO3dUW7cNhQFUMfIArKD/nT/K+pPd5AduAgKIxPBY49GEt995DlfreFYFEfi5ZM40re3t7cXAGCs18HbAwAEMADUUAEDQAEBDAAFBDAAFBDAAFBAAANAAQEMAAUEMAAUEMAAUEAAA0ABAQwABQQwABQQwABQQAADQAEBDAAFBDAAFPhesdHZ/fjr77eXID///edbdRsAWDyA08IRgDUtcwla8AKQ5HWl8BXCAKRYIoABIM3094A/qnqvWJQ0ajsAzGG5CnhUKApfOvk1gXSLBsaaugIeNaAYuOjs9vi9/W+TSLjWUhWw6heAFNMGsOoXnj9PVL9wvSkDuHJBlIGLLtw6gVpTBvCoUDSAMSOTSBhjugCuDEUDF12YPEK96QJ4S/ULj4evSSSMM1UAq34B6GKqAN5S/cKfVL+QY5oAVv0C0MkUATzya0cWr9CVYxeyTBHAlQtJLFphhvB1HMN47QN45KxeBQHAWdoH8JbqF/6k+oVMrQNY9VvT364E9OGzglxTvY5Q9TsufL22bg7u/UKdtgGs+s3pZ2GcSfUL2VoGcOXbjkZvq9sALoz7fHarHMeQqmUAjxxIVq0iHnli0ld9I4wBJgrg6kCcvWrY86jC2//fE8Yf/S3Oo/qFHtoF8JbqN+M5wXvCePs7wnieCSowaQBXDy4zB8WZD+nf/r7qGKB5AG+pfnu8HefZ6njmCc/IxYku/0OmNgGs+h3bp1eF394w5jH3+lIfQ64WT8Ia/bWjFQathPfCVlS4Kz3N66P+dVUBcrSpgCsHkZkGrYTgrWrLZ0/zunrbCZeegSzxATx6EJl50OoQvgnvce4UzHv2K7H9sLL4AN5S/fYO35R2PKNLMKt+oYfoAJ65Gl0x8KrasmcNwdHHb361jV+/e9a+7tmvtEkCEB7AoweR2b6uIXz3L+AbEcwA0QFs8Jq/8h09oTri7GA+uu+fTSycO9BDZABXvO1olkGrQ/COaMuo0N/71K+kqh6oFRnACQNIx0FL+GavsH5fHOU77EBkAFdUojNUv8L3c2eH3p7QPbMdql+YR1wAb6l++wRvwld1rr598Wzwjtj2DBNJWElUAKt+z+uvle73ftaGM7ZdGbpHttnxNgqsJCqA0we0JAmBl9SWsydvaaH71eRC9Qv9xASw6vd4P614yfmKNnx1LCZNcLpPJGFl31f92lHHQSspfFPaMnICkHR8JLUFaBzAFYNLt0t2KYGX1paz25AyGdzTnm7HMhASwCmDR0JwdAi7pPaMCMu08O18LANhAbyl+s0Mu5T7vZ+1ZYXgUf3CPEoDWPXbt9KsasuVx03K8XhkgrHCJARmEVUBq357hV1Se2ZadPXoRCBpwgDs9/pSJGXwSKoYuoRdWntGPmyjiuoX5lMSwFX377oOsvde7F4VdkmTlqvaklT9Vnz+wCKXoKsGu6QgeaZ9ewbhR/c1repdadHVkVBN7Yur3/4EnQ0P4KqZe5eK4apX1h3d/5nDN/nY6Fz9vrdTCENoBaz63d8nowfgtPC9Wsr97UfbkVZhdpkgwFIBrPo9t0r+6Odn9nv1wD7qeHnfz9uK7fbnHP/MVMEQVgGrfo/13XawuzfI7ennhPBJeTHH7c+u7I8Rk6mrpb3AAjoYFsCq39oQ3vM3Xwo8cnykTAquvv+85+8nBFvqwj1I9321FayzDQhXhPBIKe/d3fNu3aqrBGnVr6oXjvn29vY2/ERNeYn5TDrt694gSal8z27j3s+s6jx6pC0djjtYrgJOmrXPPDB0qISTjoWzK+O9l6j39kVK36l6ofEirMrqd3aJIfzMvd1Ri59GhPH23z3698/83bOoeqHRoyiTQjBpIF9hP3999o9US5+t2k7Zl6OP5Nz2xdFLzxWELzSvgFW/4/p5O+CnPGu768Mlzli89ejv7Nnm1QQvNKyAE2bt3QbzK135eRypdmfy7P599e+2fTfq3BK+0HAVdOWK3E6rgTv3Rfr3dkd7ZAJy5PMY+R5kwQsTXYKuHIhXCoERi7IE774+ue3r7SMvz3D2d5KFLzSugFW/eY5+JkL3ub75amHVWd8dfnSbFX8XKAzgygUjBo37ffNI/wje5/omYcHbWRMs5xA0CeCE+68JbUj1SN8I3ef68V5/JgexqhcmDuC0hwW8WzmQ74Wwfnuu72778KXQ3jBN3hdYxWkBnFJ5PrPAZbUBZ08fVT9FK+Wz6RJYRxd4Je0LzO6yryGlnMgC+bl+Sfj8Eh5a0aGfur/wAlY15G1ISQTy/b5IG4STHuayldZX97i1ALmWC+Ct1QM56WpFlwBO7a8Ot4iA35YP4K3VA3k2Z4b4DJ/z2Q/uAJ4ngL/gEt7aBBZwFQG8k0t5AGv4cfEtuqGvI5zBMw+uAOB6P5qNxwL4IPfSxkheLAasEZhnE8C0OWlWPVlNPEiw6vl3JfeAm3NSMCOTjuNWHRt+NrpSJoBPtupBDzB7YJ5t6kvQwvA6K580IzmGSeK8b1oBG0iu46RgJsaK8xgbsk1dAVdx0IPzZy8r/dczfQALQ6ADY9V6hgawAwwA/mcVNAAUeK3YKACsTgADQAEBDAAFBDAAFBDAAFBAAANAAQEMAAUEMAAUEMAAUEAAA0ABAQwABQQwALyM9x/5UUc/VdvvKgAAAABJRU5ErkJggg==','base64'))},values={name:'Testlejer',agreementDate:'2026-10-03',rentalDate:'2026-12-12',signature:'Testlejer'};
const source=id=>new Uint8Array(fs.readFileSync(path.join(root,ctx.HjortContracts.templates[id].path)));
for(const id of ['member-pdf','friend-pdf'])test('handwritten signature is embedded in '+id+' with an editable printed name',async()=>{
 const doc=await ctx.PDFLib.PDFDocument.load(await ctx.HjortContracts.build(id,source(id),values,ink));
 assert.equal(doc.getPageCount(),1);assert.equal(doc.getForm().getTextField('signature').getText(),'Testlejer');
 const resources=doc.getPage(0).node.Resources(),images=doc.context.lookup(resources.get(ctx.PDFLib.PDFName.of('XObject')));
 const signature=images.entries().map(([,ref])=>doc.context.lookup(ref)).find(obj=>obj.dict.get(ctx.PDFLib.PDFName.of('Width'))?.asNumber()===480&&obj.dict.get(ctx.PDFLib.PDFName.of('Height'))?.asNumber()===120);
 assert.ok(signature,'actual PNG image is in the page resources');assert.ok(signature.dict.get(ctx.PDFLib.PDFName.of('SMask')),'transparent ink retains its alpha mask');
 const fieldRect=doc.getForm().getTextField('signature').acroField.getWidgets()[0].getRectangle();assert.ok(fieldRect.y+(fieldRect.height)<(id==='friend-pdf'?76:101),'name appearance must remain below the handwritten image');
});
test('Word embeds the exact handwritten PNG and a valid image relationship while preserving legal clauses',async()=>{
 const before=ctx.fflate.unzipSync(source('member-word')),after=ctx.fflate.unzipSync(await ctx.HjortContracts.build('member-word',source('member-word'),values,ink));
 const media=Object.keys(after).filter(n=>!before[n]);assert.equal(media.length,1);assert.deepEqual(Buffer.from(after[media[0]]),Buffer.from(ink.png));
 const xml=ctx.fflate.strFromU8(after['word/document.xml']),rels=ctx.fflate.strFromU8(after['word/_rels/document.xml.rels']);
 const embed=xml.match(/<a:blip\b[^>]*r:embed="([^"]+)"/g).find(s=>s.includes('HjortSignature'));assert.ok(embed,'signature drawing must reference its own relationship');
 assert.match(rels,/Id="rIdHjortSignature"[^>]*Target="media\/hjortemosen-signature.png"/);assert.match(xml,/<wp:inline\b/);assert.match(xml,/Testlejer/);
 for(const name of Object.keys(before))if(!['word/document.xml','word/_rels/document.xml.rels'].includes(name))assert.deepEqual(after[name],before[name],name);
 const paras=x=>ctx.fflate.strFromU8(x).match(/<w:p\b[^>]*>[\s\S]*?<\/w:p>/g),a=paras(before['word/document.xml']),b=paras(after['word/document.xml']);
 for(let i=8;i<30;i++)assert.equal(a[i],b[i],'legal paragraph '+i);
});
test('invalid signature image cannot silently produce an unsigned contract',async()=>{
 await assert.rejects(ctx.HjortContracts.build('member-pdf',source('member-pdf'),values,{png:new Uint8Array([1,2,3])}),/underskrift/i);
 await assert.rejects(ctx.HjortContracts.build('member-word',source('member-word'),values,{png:new Uint8Array([1,2,3])}),/underskrift/i);
});
module.exports={ink};
